apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: dapp
  name: dapp
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: dapp
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: dapp
    spec:
      containers:
        - image: schadokar/eth-server:1.0.0
          name: dapp
          ports:
            - containerPort: 4000
          resources: {}
      restartPolicy: Always
status: {}
