apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: my-role-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: ashwani
roleRef:
  kind: Role
  name: admin
  apiGroup: rbac.authorization.k8s.io
